package by.http.newsportal.controller;

public enum CommandName {
	GO_TO_MAIN_PAGE,
	GO_TO_AUTHORIZATION_PAGE,
	GO_TO_AUTHORIZATION_INFO_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_REGISTRATION_INFO_PAGE,
	GO_TO_ADD_NEWS_PAGE,
	
	CHANGE_LOCAL,
	REGISTRATION,
	AUTHORIZATION,
	ADD_NEWS,
	UNKNOWN_COMMAND
}
