package by.http.newsportal.controller;

public enum CommandName {
	GO_TO_MAIN_PAGE,
	GO_TO_LOG_IN_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_ADD_NEWS_PAGE,
	GO_TO_REGISTRATION_INFO_PAGE,
	GO_TO_LOG_IN_INFO_PAGE,
	
	CHANGE_LOCAL,
	REGISTRATION,
	LOG_IN,
	ADD_NEWS,
	UNKNOWN_COMMAND
}
